name: Star Wars Case | Power of Data CI/CD

on:
  push:
    branches:
    - dev

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python Virtual ENV
        run: pip3 install virtualenv 

      - name: Virtual ENV
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: /

      - name: Activate Virtual ENV
        run: |
          python -m venv venv &&
          source venv/bin/activate &&
          pip3 install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Run Unit Tests
        run: |
          . venv/bin/activate &&
          python -m unittest discover -s tests

      - name: Create archive of dependencies
        run: |
          cd ./venv/lib/python3.9/site-packages &&
          zip -r9 ../../../../src.zip .

      - name: Add API files to Zip file
        run: |
          cd ./src &&
          zip -g ../src.zip *.py

      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: src
          path: src.zip

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Download Lambda src.zip
        uses: actions/download-artifact@v2
        with:
          name: src

      - name: Upload to S3
        run: aws s3 cp src.zip s3://starwarscasepod/src.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy new Lambda
        run: aws lambda update-function-code --function-name starwarscasepod --s3-bucket starwarscasepod --s3-key src.zip
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}