name: Star Wars Case | Power of Data CI/CD

on:
  push:
    branches:
    - dev

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python Virtual ENV
        run: pip3 intall virtualenv 

      - name: Virtual ENV
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: /

        - name: Activate Virtual ENV
          run: python -m venv venv && source/bin/activate && pip3 install -r requirements.txt
          if: steps.cache-venv.outputs.cache-hit != 'true'

        - name: Run Unit Tests # talvez esse de erro
          run: . venv/bin/activate && unittest

        - name: Create archive of dependencies
          run: /
            cd ./venv/lib/python3.9/site-packages
            zip -r9 ../../../../api.zip .
          
        - name: Add API files to Zip file
          run: cd ./api && zip -g ../api.zip ir .

        - name: Upload zip file artifact
          uses: actions/upload-artifact@v2
          with:
            name: api
            path: api.zip


